ALTER TABLE "bar_tags" ALTER COLUMN "sport" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "bar_tags" ALTER COLUMN "music" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "bar_tags" ALTER COLUMN "student" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "bar_tags" ALTER COLUMN "bistro" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "bar_tags" ALTER COLUMN "drink" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "bar_tags" ALTER COLUMN "joy" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "bar_tags" ALTER COLUMN "romantic" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "bar_tags" ALTER COLUMN "oldschool" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "bar_tags" ALTER COLUMN "highlevel" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "bar_tags" ALTER COLUMN "easy" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "sport" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "music" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "student" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "bistro" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "drink" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "joy" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "romantic" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "oldschool" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "highlevel" SET DATA TYPE boolean;--> statement-breakpoint
ALTER TABLE "user_tags" ALTER COLUMN "easy" SET DATA TYPE boolean;